import Head from 'next/head';

import Annoucement from '../components/Annoucement';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export default function Contact() {

  return (
    <>
      <Head>
        <title>happy kamp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#282828" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Annoucement />
        <Navbar />

        <div className="max-w-3xl mx-auto">
          <div>
            <div className="text-3xl text-center my-10">Contact Us</div>
            <div className="flex justify-between text-center py-5">
              <div className="w-[240px]">
                <div className="mb-5">VISIT US</div>
                <div>
                  <div>500 Terry Francois St.</div>
                  <div>San Francisco, CA 94158</div>
                  <div>123-456-7890</div>
                </div>
              </div>

              <div className="w-[240px]">
                <div className="mb-5">OPENING HOURS</div>
                <div>
                  <div>Mon - Fri: 7am - 10pm</div>
                  <div>Saturday: 8am - 10pm</div>
                  <div>​Sunday: 8am - 11pm</div>
                </div>
              </div>

              <div className="w-[240px]">
                <div className="mb-5">CUSTOMER SERVICE</div>
                <div>
                  <div>1-800-000-000</div>
                  <div>123-456-7890</div>
                  <div>info@mysite.com</div>
                </div>
              </div>
            </div>
          </div>

          <div className="py-20">
            <div className="text-center mb-10">FOR ANY QUESTIONS, PLEASE SEND US A MESSAGE</div>
            <form>
              <div className="flex gap-5 mb-2">
                <div className="flex flex-1 flex-col gap-2">
                  <label>First Name</label>
                  <input className="border-b border-primary-1" />
                </div>
                <div className="flex flex-1 flex-col gap-2">
                  <label>Last Name</label>
                  <input className="border-b border-primary-1" />
                </div>
              </div>
              <div className="flex flex-col gap-2 mb-2">
                <label>Email</label>
                <input className="border-b border-primary-1" />
              </div>
              <div className="flex flex-col gap-2 mb-2">
                <label>Subject</label>
                <input className="border-b border-primary-1" />
              </div>
              <div className="flex flex-col gap-2 mb-2">
                <label>Message</label>
                <textarea rows={4} className="border-b border-primary-1" />
              </div>
              <div className="flex justify-center mt-3">
                <button className="px-8 py-2">Submit</button>
              </div>
            </form>
          </div>

          {/* TODO: Add map using GEOAPIFY */}
        </div>

        <Footer />
      </main>
    </>
  )
}