import { GetServerSideProps, InferGetServerSidePropsType } from 'next';
import Head from 'next/head';
import { colors } from 'tailwindcss/defaultTheme';

import Footer from '../components/Footer';
import Annoucement from '../components/Annoucement';
import Navbar from '../components/Navbar';

interface Media {
  url: string,
  index: number,
  mediaType: string,
  altText: string | null,
  title: string
}

interface Product {
  id: string,
  name: string,
  price: number,
  discountedPrice: number,
  urlPart: string,
  media: Media[]
}

export const getServerSideProps: GetServerSideProps<{ newProducts: Product[], landImgs: string[] }> = async (context) => {
  const resNewProducts = await fetch('https://skillkamp-api.com/v1/api/products/new_arrivals');
  const resLandImgs = await fetch('https://skillkamp-api.com/v1/api/images/landing');

  const newProducts = await resNewProducts.json();
  const landImgs = await resLandImgs.json();

  return {
    props: {
      newProducts: newProducts.detail.data.catalog.category.productsWithMetaData.list,
      landImgs: landImgs.detail
    },
  }
}

export default function Home({ newProducts, landImgs }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>happy kamp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#282828" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Annoucement />

        <Navbar />

        {/* Courasal */}
        <div>
          {landImgs.map((d, i) =>
            <img key={i} src={d} width="200px" />
          )}
        </div>

        {/* New Arrivavls */}
        <div>
          {newProducts.map((d, i) =>
            <div key={i}>
              {d.media.map((md, mi) =>
                <img key={mi} src={md.url} width="100px" />
              )}
              <div>{d.name}</div>
              <div>{d.price}</div>
            </div>
          )}
        </div>

        <Footer />
      </main>
    </>
  )
}
