import { useState } from 'react';
import { GetServerSideProps, InferGetServerSidePropsType } from 'next';
import Head from 'next/head';

import Footer from '../components/Footer';
import Annoucement from '../components/Annoucement';
import Navbar from '../components/Navbar';
import Carousel from '../components/Carousel';
import ProductCard from '../components/ProductCard';
import QuickViewModal from '../components/QuickViewModal';

export interface ProductType {
  id: string,
  name: string,
  price: number,
  discountedPrice: number,
  urlPart: string,
  sku: string,
  inventory: {
    quantity: number
  },
  options: Array<{
    id: string,
    key: string
  }>,
  media: Array<{
    url: string,
    index: number,
    mediaType: string,
    altText: string | null,
    title: string
  }>
}

export const getServerSideProps: GetServerSideProps<{ newProducts: ProductType[], landImgs: string[] }> = async (context) => {
  const resNewProducts = await fetch('https://skillkamp-api.com/v1/api/products/new_arrivals');
  const resLandImgs = await fetch('https://skillkamp-api.com/v1/api/images/landing');

  const newProducts = await resNewProducts.json();
  const landImgs = await resLandImgs.json();

  return {
    props: {
      newProducts: newProducts.detail.data.catalog.category.productsWithMetaData.list,
      landImgs: landImgs.detail
    },
  }
}

export default function Home({ newProducts, landImgs }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const [quickViewProduct, setQuickViewProduct] = useState<ProductType | null>(null);

  return (
    <>
      <Head>
        <title>happy kamp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#282828" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {quickViewProduct &&
          <QuickViewModal product={quickViewProduct} onClose={() => setQuickViewProduct(null)} />
        }

        <Annoucement />

        <Navbar />

        <Carousel images={landImgs} />

        {/* New Arrivavls */}
        <div className="py-5">
          <div className="text-3xl mt-10 mb-5 text-center">New Arrivals</div>
          <div className="flex hide-scrollbar overflow-x-scroll snap-mandatory snap-x px-8 pb-4">
            {newProducts.map((d, i) =>
              <ProductCard key={i} onOpenQuickView={() => setQuickViewProduct(d)} product={d} />
            )}
          </div>
          <div className="flex justify-center mt-14">
            <button>Shop All</button>
          </div>
        </div>

        <Footer />
      </main>
    </>
  )
}
