import { useState, useEffect, ReactNode } from 'react';
import Head from 'next/head';

import Footer from './Footer';
import Navbar from './Navbar';
import Annoucement from './Annoucement';
import CartModal from './CartModal';

interface PropsType {
  title?: string,
  children: ReactNode,
  cartItems: unknown[]
}

export default function Layout ({ title, children, cartItems }: PropsType) {
  const [isCartOpen, setIsCartOpen] = useState(false);

  return (
    <>
      <Head>
        <title>{title ? title + ' | happy kamp' : 'happy kamp'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#282828" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CartModal cartItems={cartItems} isOpen={isCartOpen} onClose={() => setIsCartOpen(false)} />
        <Annoucement />
        <Navbar cartNumber={cartItems.length} onOpenCart={() => setIsCartOpen(true)} />
        {children}
        <Footer />
      </main>
    </>
  )
}